version: "3.8"

services:
  # --- FRONTENDY ---
  web:
    container_name: plane-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.web
      args:
        NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}
        NEXT_PUBLIC_WEB_URL: ${WEB_URL}
        NEXT_PUBLIC_GOOGLE_CLIENTID: ${GOOGLE_CLIENTID}
    restart: always
    expose:
      - "3000"
    depends_on:
      - api
      - worker

  admin:
    container_name: plane-admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile.admin
      args:
        NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}
        NEXT_PUBLIC_WEB_URL: ${WEB_URL}
    restart: always
    expose:
      - "3000"
    depends_on:
      - api

  space:
    container_name: plane-space
    build:
      context: .
      dockerfile: ./apps/space/Dockerfile.space
      args:
        NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}
        NEXT_PUBLIC_WEB_URL: ${WEB_URL}
    restart: always
    expose:
      - "3000"
    depends_on:
      - api

  live:
    container_name: plane-live
    build:
      context: .
      dockerfile: ./apps/live/Dockerfile.live
    restart: always
    expose:
      - "3000"

  # --- BACKEND & WORKERS ---
  api:
    container_name: plane-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
    restart: always
    command: ./bin/docker-entrypoint-api.sh
    expose:
      - "8000"
    depends_on:
      - plane-db
      - plane-redis
      - plane-mq

  worker:
    container_name: plane-bgworker
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
    restart: always
    command: ./bin/docker-entrypoint-worker.sh
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    container_name: plane-beatworker
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
    restart: always
    command: ./bin/docker-entrypoint-beat.sh
    depends_on:
      - api
      - plane-db
      - plane-redis

  migrator:
    container_name: plane-migrator
    build:
      context: ./apps/api
      dockerfile: Dockerfile.api
    restart: "no"
    command: ./bin/docker-entrypoint-migrator.sh
    depends_on:
      - plane-db
      - plane-redis

  # --- INFRASTRUKTURA ---
  plane-db:
    container_name: plane-db
    image: postgres:15.7-alpine
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-plane}
      POSTGRES_DB: ${POSTGRES_DB:-plane}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data

  plane-redis:
    container_name: plane-redis
    image: valkey/valkey:7.2.11-alpine
    restart: always
    volumes:
      - redisdata:/data

  plane-mq:
    container_name: plane-mq
    image: rabbitmq:3.13.6-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-plane}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-plane}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  plane-minio:
    container_name: plane-minio
    image: minio/minio
    restart: always
    command: server /export --console-address ":9090"
    volumes:
      - uploads:/export
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}

volumes:
  pgdata:
  redisdata:
  uploads:
  rabbitmq_data: