name: Build Frontend (Turbo ARM)

on:
  push:
    branches: [ "preview", "master" ]
    paths:
      - "apps/web/**"
      - ".github/workflows/build-frontend.yml"

env:
  REGISTRY: ghcr.io
  # Změňte na svůj GitHub username a název repa (malá písmena!)
  IMAGE_NAME: ${{ github.repository }}-frontend

jobs:
  build-and-push:
    runs-on: self-hosted   # <--- TOTO JE TA ZMĚNA (použije váš server)
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true  

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/web/Dockerfile.web
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # Žádné platforms, žádné QEMU = maximální rychlost
